name: Add activity table

on:
  push:
  schedule:   
    - cron:  '30 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_contributions_table:
    runs-on: ubuntu-latest
    #if: github.event.pusher.name != 'SebastianZug'
    steps:
      # Checkout repository
      #- name: Check out current repository
      #  uses: actions/checkout@v2
        #with:
        #    path: "repository/Versions/repo/"

      - name: Show repo
        run: |
             git clone https://github.com/SebastianZug/SoftwareentwicklungSoSe2021_Aufgabe_08.git .
             git log

      - name: Show version
        run: |
             # cd repository/Versions/repo/
             git show 3d79c4a62b253551d19bd36bb0e97dc1e9a1d7bf

      - name: Install pipenv
        run: | 
             pip install pipenv
             pipenv --python 3.8
             pipenv install github2pandas 
             pipenv install tabulate
             cat Pipfile

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Print environment variables
        run: |
             echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
             echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"

      - name: Run generation script
        env: 
             TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             cp  repository/Versions/repo/.github/workflows/embedTable.py .
             pipenv run python embedTable.py 
             cat repository/Versions/repo/README.md
         
      - name: Commit files
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git add repository/Versions/repo/README.md
             git commit -m "Add new statistics" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: main
